spring.datasource.url=jdbc:postgresql://localhost:5432/db_learning
spring.datasource.username=root
spring.datasource.password=adminadmin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect